### ISSUE TITLE
Stripe error(i want to try the program it self, not the link =))

### ISSUE THREAD

**Issue by darius-luca-tech** [FlorianWoelki/lungcure#10]
Stripe Checkout can't communicate with our payment processor because the API key is invalid. Please contact the website owner or support@stripe.com. 

Any ideas?How can I solve it or remove the payment mode?

**Comment by FlorianWoelki** [comment]
You need to have an account on stripe.

Then you can follow the configuration steps.
You need to do the following things:
1. Create a copy of sample.env with the name production.env within the app directory.
2. Update pub_key and secret_key within the production.env file with account specific keys.

You can also remove the payment process by removing the stripe api in the html files.
